import json
import pandas as pd

# -------------------------------------------------------------------------                                                                                                                                                           
# VQAv2                                                                                                                                                                                                                          
# -------------------------------------------------------------------------       
def prep_prompt_vqav2(question_id: int, model_id: str) -> str:
    """Prepares a prompt for VQAv2-style questions with an image."""
    VQAV2_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vqav2/llava_vqav2_mscoco_test2015.jsonl"
    VQAV2_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vqav2/answers/llava_vqav2_mscoco_test-dev2015/{model_id}/merge.jsonl"

    image_root = (
        "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vqav2/test2015"
    )
    with open(VQAV2_QUESTION_PATH, "r") as f:
        for line in f:
            item = json.loads(line)
            if item["question_id"] == question_id:
                question = item["text"]
                image_path = f"{image_root}/{item['image']}"
                break

    with open(VQAV2_MODEL_ANS, "r") as f:
        for line in f:
            item = json.loads(line)
            if item["question_id"] == question_id:
                model_answer = item["text"]
                break
    return (    
        image_path,
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",
    )

# -------------------------------------------------------------------------                                                                                                                                                           
# TextVQA                                                                                                                                                                                                                          
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_textvqa(question_id: str, model_id: str) -> tuple[str, str]:                                                                                                                                                          
    """Prepares a prompt for TextVQA questions with an image."""                                                                                                                                                                      
    TEXTVQA_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/textvqa/llava_textvqa_val_v051_ocr.jsonl"                                                                                                
    TEXTVQA_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/textvqa/answers/{model_id}.jsonl"                                                                                                           
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/textvqa/train_images"                                                                                                                               
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(TEXTVQA_QUESTION_PATH, "r") as f:                                                                                                                                                                                       
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item["question_id"]) == str(question_id):                                                                                                                                                                          
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(TEXTVQA_MODEL_ANS, "r") as f:                                                                                                                                                                                           
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item["question_id"]) == str(question_id):                                                                                                                                                                          
                model_answer = item["text"]                                                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                   

# -------------------------------------------------------------------------                                                                                                                                                           
# 2. OCR_Bench                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_ocrbench(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                         
    """Prepares a prompt for OCR_Bench questions with an image."""                                                                                                                                                                    
    OCRBENCH_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/ocr_bench/OCRBench.json"                                                                                                                
    OCRBENCH_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/ocr_bench/{model_id}.json"                                                                                                                 
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/ocr_bench/OCRBench_Images"                                                                                                                          
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(OCRBENCH_QUESTION_PATH, "r") as f:                                                                                                                                                                                      
        ocr_data = json.load(f)                                                                                                                                                                                                       
        for item in ocr_data:                                                                                                                                                                                                         
            if item.get("id") == question_id:                                                                                                                                                                                         
                question = item["question"]                                                                                                                                                                                           
                image_path = f"{image_root}/{item['image_path']}"                                                                                                                                                                     
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(OCRBENCH_MODEL_ANS, "r") as f:                                                                                                                                                                                          
        ans_data = json.load(f)                                                                                                                                                                                                       
        for item in ans_data:                                                                                                                                                                                                         
            if item.get("id") == question_id:                                                                                                                                                                                         
                model_answer = item.get("predict", "")                                                                                                                                                                                
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 3. MMMU                                                                                                                                                                                                                             
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_mmmu(question_id: str, model_id: str) -> tuple[str, str]:                                                                                                                                                             
    """Prepares a prompt for MMMU college-level multidisciplinary questions."""                                                                                                                                                       
    MMMU_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/MMMU/answers/{model_id}/merge.jsonl"                                                                                                           
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/MMMU/images"                                                                                                                                        
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(MMMU_MODEL_ANS, "r") as f:                                                                                                                                                                                              
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item.get("id")) == str(question_id):                                                                                                                                                                               
                question = item.get("question", item.get("prompt", ""))                                                                                                                                                               
                img_name = item.get("image", f"{question_id}.png")                                                                                                                                                                    
                image_path = f"{image_root}/{img_name}"                                                                                                                                                                               
                model_answer = item.get("parsed_pred", item.get("response", item.get("text", "")))                                                                                                                                    
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 4. MMBench                                                                                                                                                                                                                          
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_mmbench(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                          
    """Prepares a prompt for MMBench questions."""                                                                                                                                                                                    
    MMBENCH_TSV_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mmbench/mmbench_dev_20230712.tsv"                                                                                                             
    MMBENCH_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mmbench/answers/mmbench_dev_20230712/{model_id}.jsonl"                                                                                      
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mmbench/images"                                                                                                                                     
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    df = pd.read_csv(MMBENCH_TSV_PATH, sep="\t")                                                                                                                                                                                      
    row = df[df["index"] == question_id]                                                                                                                                                                                              
    if not row.empty:                                                                                                                                                                                                                 
        r = row.iloc[0]                                                                                                                                                                                                               
        question = (                                                                                                                                                                                                                  
            f"{r['question']}\n"                                                                                                                                                                                                      
            f"A. {r['A']}\nB. {r['B']}\nC. {r['C']}\nD. {r['D']}\n"                                                                                                                                                                   
            "Answer with the option's letter from the given choices directly."                                                                                                                                                        
        )                                                                                                                                                                                                                             
        image_path = f"{image_root}/{question_id}.jpg"                                                                                                                                                                                
                                                                                                                                                                                                                                        
    with open(MMBENCH_MODEL_ANS, "r") as f:                                                                                                                                                                                           
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item.get("question_id") == question_id or item.get("index") == question_id:                                                                                                                                            
                model_answer = item.get("text", item.get("prediction", ""))                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 5. GQA                                                                                                                                                                                                                              
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_gqa(question_id: str, model_id: str) -> tuple[str, str]:                                                                                                                                                              
    """Prepares a prompt for GQA visual reasoning questions."""                                                                                                                                                                       
    GQA_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/gqa/llava_gqa_testdev_balanced.jsonl"                                                                                                        
    GQA_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/gqa/answers/llava_gqa_testdev_balanced/{model_id}.jsonl"                                                                                        
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/gqa/data/images"                                                                                                                                    
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(GQA_QUESTION_PATH, "r") as f:                                                                                                                                                                                           
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item["question_id"]) == str(question_id):                                                                                                                                                                          
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(GQA_MODEL_ANS, "r") as f:                                                                                                                                                                                               
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item["question_id"]) == str(question_id):                                                                                                                                                                          
                model_answer = item["text"]                                                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 6. POPE                                                                                                                                                                                                                             
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_pope(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                             
    """Prepares a prompt for POPE hallucination evaluation questions."""                                                                                                                                                              
    POPE_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/pope/llava_pope_test.jsonl"                                                                                                                 
    POPE_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/pope/answers/{model_id}.jsonl"                                                                                                                 
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/pope/val2014"                                                                                                                                       
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(POPE_QUESTION_PATH, "r") as f:                                                                                                                                                                                          
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(POPE_MODEL_ANS, "r") as f:                                                                                                                                                                                              
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                model_answer = item["text"]                                                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 7. DocVQA                                                                                                                                                                                                                           
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_docvqa(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                           
    """Prepares a prompt for DocVQA document understanding questions."""                                                                                                                                                              
    DOCVQA_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/docvqa/test.jsonl"                                                                                                                        
    DOCVQA_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/docvqa/answers/{model_id}/merge.jsonl"                                                                                                       
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/docvqa"                                                                                                                                             
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(DOCVQA_QUESTION_PATH, "r") as f:                                                                                                                                                                                        
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item.get("question_id") == question_id or item.get("questionId") == question_id:                                                                                                                                       
                question = item.get("question", item.get("text", ""))                                                                                                                                                                 
                image_rel = item.get("image", "")                                                                                                                                                                                     
                image_path = f"{image_root}/{image_rel}"                                                                                                                                                                              
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(DOCVQA_MODEL_ANS, "r") as f:                                                                                                                                                                                            
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item.get("question_id") == question_id or item.get("questionId") == question_id:                                                                                                                                       
                model_answer = item.get("text", item.get("answer", ""))                                                                                                                                                               
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 8. MM-Vet                                                                                                                                                                                                                           
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_mmvet(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                            
    """Prepares a prompt for MM-Vet integrated multimodal reasoning."""                                                                                                                                                               
    MMVET_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mm-vet/llava-mm-vet.jsonl"                                                                                                                 
    MMVET_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mm-vet/answers/{model_id}.jsonl"                                                                                                              
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/mm-vet/images"                                                                                                                                      
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(MMVET_QUESTION_PATH, "r") as f:                                                                                                                                                                                         
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(MMVET_MODEL_ANS, "r") as f:                                                                                                                                                                                             
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                model_answer = item["text"]                                                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 9. VizWiz                                                                                                                                                                                                                           
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_vizwiz(question_id: int, model_id: str) -> tuple[str, str]:                                                                                                                                                           
    """Prepares a prompt for VizWiz assistive VQA questions."""                                                                                                                                                                       
    VIZWIZ_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vizwiz/llava_test.jsonl"                                                                                                                  
    VIZWIZ_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vizwiz/answers/{model_id}.jsonl"                                                                                                             
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/vizwiz/test"                                                                                                                                        
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(VIZWIZ_QUESTION_PATH, "r") as f:                                                                                                                                                                                        
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(VIZWIZ_MODEL_ANS, "r") as f:                                                                                                                                                                                            
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if item["question_id"] == question_id:                                                                                                                                                                                    
                model_answer = item["text"]                                                                                                                                                                                           
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
# -------------------------------------------------------------------------                                                                                                                                                           
# 10. MME                                                                                                                                                                                                                             
# -------------------------------------------------------------------------                                                                                                                                                           
def prep_prompt_mme(question_id: str, model_id: str) -> tuple[str, str]:                                                                                                                                                              
    """Prepares a prompt for MME perception/cognition benchmark questions."""                                                                                                                                                         
    MME_QUESTION_PATH = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/MME/llava_mme.jsonl"                                                                                                                         
    MME_MODEL_ANS = f"/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/MME/answers/{model_id}.jsonl"                                                                                                                   
    image_root = "/g/home/orachat.c/project/MLLM/TokenPacker/playground/data/eval/MME/MME_Benchmark_release_version"                                                                                                                  
                                                                                                                                                                                                                                        
    question, image_path, model_answer = "", "", ""                                                                                                                                                                                   
    with open(MME_QUESTION_PATH, "r") as f:                                                                                                                                                                                           
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item["question_id"]) == str(question_id) or str(item["image"]) == str(question_id):                                                                                                                                
                question = item["text"]                                                                                                                                                                                               
                image_path = f"{image_root}/{item['image']}"                                                                                                                                                                          
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    with open(MME_MODEL_ANS, "r") as f:                                                                                                                                                                                               
        for line in f:                                                                                                                                                                                                                
            item = json.loads(line)                                                                                                                                                                                                   
            if str(item.get("question_id")) == str(question_id) or str(item.get("image")) == str(question_id):                                                                                                                        
                model_answer = item.get("text", "")                                                                                                                                                                                   
                break                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
    return (                                                                                                                                                                                                                          
        image_path,                                                                                                                                                                                                                   
        f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{question} ASSISTANT: {model_answer}",            
    )                                       
